variable "code_commit_name" {}
variable "code_commit_desc" {}
#variable "terraform_plan_name" {}
variable "bucket_name" {}
variable "s3_logging_bucket" {}
#variable "s3_logging_bucket_id" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "acl_value" {}
variable "region" {}
variable "key" {}
variable "profile" {}
variable "codebuild_iam_role_name" {}
variable "codebuild_project_terraform_plan_name" {}
#variable "codebuild_iam_role_arn" {}
variable "tf_codepipeline_name" {}
variable "tf_codepipeline_artifact_bucket_name" {}
variable "tf_codepipeline_role_name" {}
variable "tf_codepipeline_role_policy_name" {}
variable "codebuild_project_terraform_apply_name" {}
variable "state_bucket_arn" {}
variable "tf_iam_assumedRole" {}
variable "tf_iam_assumedPolicy" {}
variable "aws_access_key_2" {}
variable "aws_secret_key_2" {}
variable "acl_value_2" {}
variable "codebuild_iam_role_policy_name" {}
variable "codecommit_role" {}
variable "codecommit_policy" {}