variable "repo_name" {}
variable "code_commit_desc" {}
variable "region" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "profile" {}
variable "codecommit_policy" {}
variable "codecommit_role" {}
variable "codebuild_project_name" {}
variable "codebuild_iam_role_name" {}
variable "tf_iam_assumedPolicy" {}
variable "s3_bucket_logs" {}
variable "bucket" {}
variable "tf_codepipeline_role_policy_name" {}
variable "tf_codepipeline_role_name" {}
variable "lambda_policy" {}
variable "lambda_role" {}
variable "lambda_artifact_key" {}
variable "target_access_key" {}
variable "target_secret_key" {}
variable "tf_code_pipeline_name" {}
variable "branch" {}
variable "codepipeline_artifact" {}
variable "lambda_service_role" {}
variable "lambda_assumedPolicy" {}